import type { Metadata } from "next";
import seed from "./seed.data.json";
import { ExampleCharts } from "./ExampleCharts";

export const metadata: Metadata = {
  title: "Example audit report | StratVerity",
  description:
    "A real StratVerity audit report, end to end: recomputed net-of-fees metrics, detected biases and a sealed SHA-256 verdict. No login, no email.",
  openGraph: {
    title: "StratVerity — Example audit report",
    description:
      "A real audit, end to end. Recomputed metrics, detected biases, sealed SHA-256 verdict. Judge us on the report.",
    type: "website",
    url: "https://www.stratverity.com/example",
  },
};

const S = {
  label: { color: "#8B98A5", font: "700 12px/1 var(--mono)", letterSpacing: ".14em" } as const,
  h1: { fontFamily: "var(--display)", fontSize: "clamp(1.9rem, 4.5vw, 3rem)", letterSpacing: "-.04em" } as const,
  sub: { color: "#8B98A5", fontSize: 15, lineHeight: 1.6 } as const,
  card: { background: "var(--surface-2)", border: "1px solid var(--border-soft)", borderRadius: 14, padding: "20px 24px" } as const,
  mono: { fontFamily: "var(--mono)", fontSize: 13 } as const,
};

const GREEN = "#00FF9D";
const RED = "#EF4444";
const AMBER = "#F59E0B";

export default function ExamplePage() {
  const m = seed.metrics;
  const prov = seed._provenance;
  const mm = seed.visible_bias.mismatch.net_profit;

  return (
    <main style={{ width: "min(980px, calc(100% - 32px))", margin: "0 auto", padding: "52px 0 96px" }}>
      {/* Bannière lot initial (amber, discret) */}
      <div
        style={{
          ...S.card,
          border: `1px solid ${AMBER}66`,
          color: AMBER,
          fontSize: 13,
        }}
      >
        EXAMPLE REPORT — generated by the engine on a model strategy (seed batch). Client seals appear as real audits complete.
      </div>

      {/* En-tête scellé */}
      <div style={{ marginTop: 30 }}>
        <span style={S.label}>EXAMPLE · STRATEGY #SV-002</span>
        <h1 style={S.h1}>This is what proof looks like.</h1>
        <p style={S.sub}>
          A real audit report, end to end. No login. No email. Judge us on the report, not the landing page.
        </p>
        <div style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" }}>
          <span style={{ ...S.mono, color: AMBER, border: `1px solid ${AMBER}88`, borderRadius: 8, padding: "4px 10px" }}>
            verdict: FAIL
          </span>
          <span style={{ ...S.mono, color: "#8B98A5", padding: "4px 10px" }}>seal {prov.seal_short}…</span>
          <a
            href={`/verify/${prov.seal}`}
            style={{ ...S.mono, color: GREEN, padding: "4px 10px", textDecoration: "none" }}
          >
            verify on-chain →
          </a>
        </div>
      </div>

      {/* 4 métriques mono */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 14, marginTop: 26 }}>
        {[
          ["Net P&L", `${m.net_profit >= 0 ? "+" : ""}${m.net_profit}`, GREEN],
          ["Profit Factor (net, annuel)", `${m.pf_2023} – ${m.pf_2025}`, m.pf_2023 > 1 ? GREEN : "#8B98A5"],
          ["Max drawdown", `${m.max_dd_pct}%`, RED],
          ["Biases detected", `${seed.locked_biases.length + 1}`, AMBER],
        ].map(([k, v, c]) => (
          <div key={k} style={{ ...S.card, padding: "16px 18px" }}>
            <div style={{ ...S.label, fontSize: 11 }}>{k}</div>
            <div style={{ ...S.mono, color: c, fontSize: 19, marginTop: 6 }}>{v}</div>
          </div>
        ))}
      </div>

      {/* AVG R — honnêteté E-3 */}
      <div style={{ ...S.card, marginTop: 18 }}>
        <div style={{ ...S.mono, color: GREEN }}>AVG R : N/A</div>
        <p style={{ ...S.sub, marginTop: 6 }}>
          The TradingView export format does not carry the risk basis per trade. We refuse to display a number the format
          cannot support.
        </p>
      </div>

      {/* Equity + underwater */}
      <div style={{ ...S.card, marginTop: 26 }}>
        <div style={S.label}>EQUITY (engine recompute) vs BUY&HOLD EURUSD — % of initial capital</div>
        <ExampleCharts points={seed.equity} />
        <div style={{ ...S.sub, fontSize: 12, color: "#8B98A5" }}>
          Underwater: distance to the running peak (unrealized drawdown). Benchmark: EURUSD 1h close over the same window.
        </div>
      </div>

      {/* Heatmap mensuelle */}
      <div style={{ ...S.card, marginTop: 26 }}>
        <div style={S.label}>MONTHLY NET P&L — last 12 months (% of capital)</div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(6, 1fr)", gap: 8, marginTop: 12 }}>
          {seed.heatmap.map((c) => (
            <div
              key={`${c.y}-${c.m}`}
              style={{
                padding: "10px 4px",
                background: c.pct >= 0 ? "rgba(0,255,157,0.12)" : "rgba(239,68,68,0.14)",
                borderRadius: 8,
                textAlign: "center",
              }}
            >
              <div style={{ ...S.mono, fontSize: 11, color: "#8B98A5" }}>{`${c.m.toString().padStart(2, "0")}/${c.y.slice(2)}`}</div>
              <div style={{ ...S.mono, fontSize: 12, color: c.pct >= 0 ? GREEN : RED }}>{`${c.pct >= 0 ? "+" : ""}${c.pct}`}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Biais : 1 visible + 2 verrouillés */}
      <div style={{ ...S.card, marginTop: 26 }}>
        <div style={S.label}>DETECTED BIASES — 1 / 3 unlocked</div>
        <div style={{ borderLeft: `3px solid ${RED}`, paddingLeft: 14, marginTop: 14 }}>
          <div style={{ ...S.mono, color: RED, fontWeight: 700 }}>metrics.declared_consistency — FAIL</div>
          <p style={{ ...S.sub, marginTop: 6 }}>{seed.visible_bias.message}</p>
          <div style={{ ...S.mono, color: "#8B98A5", fontSize: 12, marginTop: 8 }}>
            declared net P&L: <span style={{ color: RED }}>{mm.declared}</span> · recomputed net P&L:{" "}
            <span style={{ color: GREEN }}>{mm.calculated}</span>
          </div>
        </div>
        {seed.locked_biases.map((b) => (
          <div
            key={b.check}
            style={{
              borderLeft: `3px solid ${AMBER}`,
              paddingLeft: 14,
              marginTop: 14,
              filter: "blur(4px)",
              color: "#8B98A5",
            }}
          >
            <div style={{ ...S.mono }}>🔒 {b.check}</div>
            <div style={{ fontSize: 13, marginTop: 4 }}>{b.message}</div>
          </div>
        ))}
        <a
          href="/pricing/audit"
          style={{ display: "inline-block", marginTop: 18, padding: "12px 22px", background: GREEN, color: "#04120c", borderRadius: 10, fontWeight: 700, fontSize: 15, textDecoration: "none" }}
        >
          🔓 Unlock the full bias breakdown — from €19
        </a>
        <div style={{ fontSize: 12, color: "#8B98A5", marginTop: 6 }}>
          Read-only analysis. Code deleted right after the scan.
        </div>
      </div>

      {/* Footer proof */}
      <div style={{ paddingTop: 26, borderTop: "1px solid rgba(255,255,255,0.07)", marginTop: 26 }}>
        <p style={{ ...S.sub, fontSize: 13, color: "#8B98A5" }}>
          Your code is never stored — deleted immediately after analysis.{" "}
          <a href="/gallery" style={{ color: GREEN }}>Verify a certificate →</a>
        </p>
        <p style={{ ...S.sub, fontSize: 12, color: "#6a737d", marginTop: 6 }}>
          {prov.note} · {prov.seed} · engine {prov.engine_version} · window {prov.window}
        </p>
      </div>
    </main>
  );
}